
package com.ljw.webservice_jdk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWeatherService", targetNamespace = "http://webservice_jdk.ljw.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWeatherService {


    /**
     * 
     * @param cityName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "weather", targetNamespace = "")
    @RequestWrapper(localName = "getWeather", targetNamespace = "http://webservice_jdk.ljw.com", className = "com.ljw.webservice_jdk.GetWeather")
    @ResponseWrapper(localName = "getWeatherResponse", targetNamespace = "http://webservice_jdk.ljw.com", className = "com.ljw.webservice_jdk.GetWeatherResponse")
    @Action(input = "http://webservice_jdk.ljw.com/IWeatherService/getWeatherRequest", output = "http://webservice_jdk.ljw.com/IWeatherService/getWeatherResponse")
    public String getWeather(
        @WebParam(name = "cityName", targetNamespace = "")
        String cityName);

}
