
package com.ljw.webservice_jdk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherServiceImpl", targetNamespace = "http://webservice_jdk.ljw.com", wsdlLocation = "http://192.168.0.108:9277/web_service/weather?wsdl")
public class WeatherServiceImpl
    extends Service
{

    private final static URL WEATHERSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException WEATHERSERVICEIMPL_EXCEPTION;
    private final static QName WEATHERSERVICEIMPL_QNAME = new QName("http://webservice_jdk.ljw.com", "WeatherServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.108:9277/web_service/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERSERVICEIMPL_WSDL_LOCATION = url;
        WEATHERSERVICEIMPL_EXCEPTION = e;
    }

    public WeatherServiceImpl() {
        super(__getWsdlLocation(), WEATHERSERVICEIMPL_QNAME);
    }

    public WeatherServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERSERVICEIMPL_QNAME, features);
    }

    public WeatherServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, WEATHERSERVICEIMPL_QNAME);
    }

    public WeatherServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERSERVICEIMPL_QNAME, features);
    }

    public WeatherServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWeatherService
     */
    @WebEndpoint(name = "WeatherServicePort")
    public IWeatherService getWeatherServicePort() {
        return super.getPort(new QName("http://webservice_jdk.ljw.com", "WeatherServicePort"), IWeatherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWeatherService
     */
    @WebEndpoint(name = "WeatherServicePort")
    public IWeatherService getWeatherServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice_jdk.ljw.com", "WeatherServicePort"), IWeatherService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERSERVICEIMPL_EXCEPTION!= null) {
            throw WEATHERSERVICEIMPL_EXCEPTION;
        }
        return WEATHERSERVICEIMPL_WSDL_LOCATION;
    }

}
